### ISSUE TITLE
git install fails

### ISSUE THREAD

**Issue by heyref** [spaceml-org/STARCOP#3]
When running command pip install git+https://github.com/spaceml-org/STARCOP.git, I get the following message:

Collecting git+https://github.com/spaceml-org/STARCOP.git
  Cloning https://github.com/spaceml-org/STARCOP.git to c:\users\tanni\appdata\local\temp\pip-req-build-g2jstq2n
  Running command git clone --filter=blob:none --quiet https://github.com/spaceml-org/STARCOP.git 'C:\Users\tanni\AppData\Local\Temp\pip-req-build-g2jstq2n'
  Resolved https://github.com/spaceml-org/STARCOP.git to commit b404aa93b34ba904555a372f634767f69527435d
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tanni\AppData\Local\Temp\pip-req-build-g2jstq2n\setup.py", line 6, in <module>
          long_description = fh.read()
        File "C:\Users\tanni\anaconda3\envs\starcop_env\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5599: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by previtus** [comment]
Hello,
Thank you for your interest in running our models.
Please could you try setting up the code first on the Colab environment, for example by running this notebook - https://github.com/spaceml-org/STARCOP/blob/main/notebooks/model_demos_AVIRIS.ipynb ?

There, even if I run `!pip install git+https://github.com/spaceml-org/STARCOP.git` instead of the older commands (the field with `!pip --quiet install -r requirements.txt` and the field just under it - btw I think that both versions should work) everything seems to be working correctly.

Perhaps this could be linked to specific python or libraries versions - so getting it working first on Colab could serve as a good demo for which libraries versions to later download for a local run.
